config/routes.rb
NewApp::Application.routes.draw do
  resources :hashtags

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hashtags_controller.rb
require "rubygems"
require "twitter"


class HashtagsController < ApplicationController
  # GET /hashtags
  # GET /hashtags.xml
  def index
    @hashtags = Hashtag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hashtags }
    end
  end

  # GET /hashtags/1
  # GET /hashtags/1.xml
  def show
    @hashtag = Hashtag.find(params[:id])
    search = Twitter::Search.new
    @strstr='#'+@hashtag.Newtag
    @sss=search.hashtag(@strstr).no_retweets.per_page(1).fetch.first.text

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @hashtag }
    end
  end





  # GET /hashtags/new
  # GET /hashtags/new.xml
  def new
    @hashtag = Hashtag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hashtag }
    end
  end

  # GET /hashtags/1/edit
  def edit
    @hashtag = Hashtag.find(params[:id])
  end

  # POST /hashtags
  # POST /hashtags.xml
  def create
    @hashtag = Hashtag.new(params[:hashtag])

    respond_to do |format|
      if @hashtag.save
        format.html { redirect_to(@hashtag, :notice => 'Hashtag was successfully created.') }
        format.xml  { render :xml => @hashtag, :status => :created, :location => @hashtag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @hashtag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hashtags/1
  # PUT /hashtags/1.xml
  def update
    @hashtag = Hashtag.find(params[:id])

    respond_to do |format|
      if @hashtag.update_attributes(params[:hashtag])
        format.html { redirect_to(@hashtag, :notice => 'Hashtag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hashtag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtags/1
  # DELETE /hashtags/1.xml
  def destroy
    @hashtag = Hashtag.find(params[:id])
    @hashtag.destroy

    respond_to do |format|
      format.html { redirect_to(hashtags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/hashtags/_form.html.erb
<%= form_for(@hashtag) do |f| %>
  <% if @hashtag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hashtag.errors.count, "error") %> prohibited this hashtag from being saved:</h2>

      <ul>
      <% @hashtag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Newtag %><br />
    <%= f.text_field :Newtag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hashtags/edit.html.erb
<h1>Editing hashtag</h1>

<%= render 'form' %>

<%= link_to 'Show', @hashtag %> |
<%= link_to 'Back', hashtags_path %>

app/views/hashtags/index.html.erb
<h1>Listing hashtags</h1>

<table>
  <tr>
    <th>Newtag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hashtags.each do |hashtag| %>
  <tr>
    <td><%= hashtag.Newtag %></td>
    <td><%= link_to 'Show', hashtag %></td>
    <td><%= link_to 'Edit', edit_hashtag_path(hashtag) %></td>
    <td><%= link_to 'Destroy', hashtag, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hashtag', new_hashtag_path %>

app/views/hashtags/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', hashtags_path %>

app/views/hashtags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hashtag:</b>
  <%= @strstr %>
  <br/>
  <br/>
  <b>Tweets:</b>
  <p><%=  @sss %></p>
</p>


<%= link_to 'Edit', edit_hashtag_path(@hashtag) %> |
<%= link_to 'Back', hashtags_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>